<a href="https://colab.research.google.com/github/samurai5634/COdes/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/dataset.csv')

In [ ]:
data.head()


,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811


In [ ]:
data ['tags'] = data['genre'] + data['overview']

In [ ]:
data.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count', 'tags'],
      dtype='object')

In [ ]:
data.info

<bound method DataFrame.info of           id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre original_language  \
0                                          Drama,Crime                en   
1                                 Comedy,Drama,Romance                hi   
2                                          Drama,Crime                en   
3                                    Drama,History,War                en   
4                                          Drama,Crime                en   
...                                                ...               ...   
9995                          Action,Adventure,Fantasy                en   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure                en   
9997                        Action,Science Fiction,War                en   
9998                    Adventure,Fantasy,Action,Drama                en   
9999                             Thriller,Action,Crime                en   

                                               overview  popularity  \
0     Framed in the 1940s for the double murder of h...      94.075   
1     Raj is a rich, carefree, happy-go-lucky second...      25.408   
2     Spanning the years 1945 to 1955, a chronicle o...      90.585   
3     The true story of how businessman Oskar Schind...      44.761   
4     In the continuing saga of the Corleone crime f...      57.749   
...                                                 ...         ...   
9995  The story follows the adventures of Aang, a yo...      98.322   
9996  The sharks take bite out of the East Coast whe...      12.490   
9997  During World War II, a brave, patriotic Americ...      18.333   
9998  A man named Farmer sets out to rescue his kidn...      15.159   
9999  Seeking justice for his partner’s murder by an...      16.482   

     release_date  vote_average  vote_count  \
0      1994-09-23           8.7       21862   
1      1995-10-19           8.7        3731   
2      1972-03-14           8.7       16280   
3      1993-12-15           8.6       12959   
4      1974-12-20           8.6        9811   
...           ...           ...         ...   
9995   2010-06-30           4.7        3347   
9996   2015-07-22           4.7         417   
9997   1990-12-14           4.6         332   
9998   2007-11-29           4.7         668   
9999   2019-05-31           4.6         221   

                                                   tags  
0     Drama,CrimeFramed in the 1940s for the double ...  
1     Comedy,Drama,RomanceRaj is a rich, carefree, h...  
2     Drama,CrimeSpanning the years 1945 to 1955, a ...  
3     Drama,History,WarThe true story of how busines...  
4     Drama,CrimeIn the continuing saga of the Corle...  
...                                                 ...  
9995  Action,Adventure,FantasyThe story follows the ...  
9996  Action,TV Movie,Science Fiction,Comedy,Adventu...  
9997  Action,Science Fiction,WarDuring World War II,...  
9998  Adventure,Fantasy,Action,DramaA man named Farm...  
9999  Thriller,Action,CrimeSeeking justice for his p...  

[10000 rows x 10 columns]>

In [ ]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
 9   tags               9985 non-null   object 
dtypes: float64(2), int64(2), object(6)
memory usage: 781.4+ KB


In [ ]:
data['tags']

,tags
0,"Drama,CrimeFramed in the 1940s for the double ..."
1,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,"Drama,History,WarThe true story of how busines..."
4,"Drama,CrimeIn the continuing saga of the Corle..."
...,...
9995,"Action,Adventure,FantasyThe story follows the ..."
9996,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,"Action,Science Fiction,WarDuring World War II,..."
9998,"Adventure,Fantasy,Action,DramaA man named Farm..."


In [ ]:
data_1 = data[['id','tags','title']]

In [ ]:
data_1.head()

,id,tags,title
0,278,"Drama,CrimeFramed in the 1940s for the double ...",The Shawshank Redemption
1,19404,"Comedy,Drama,RomanceRaj is a rich, carefree, h...",Dilwale Dulhania Le Jayenge
2,238,"Drama,CrimeSpanning the years 1945 to 1955, a ...",The Godfather
3,424,"Drama,History,WarThe true story of how busines...",Schindler's List
4,240,"Drama,CrimeIn the continuing saga of the Corle...",The Godfather: Part II


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=10000,stop_words='english')

In [ ]:
data_1['tags'] = data_1['tags'].fillna('')

/tmp/ipython-input-16-3825542859.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['tags'] = data_1['tags'].fillna('')


In [ ]:
vec = cv.fit_transform(data_1['tags']).toarray()

In [ ]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
sin = cosine_similarity(vec)

In [ ]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
sin

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

In [ ]:
data_1 [data_1['title'] == 'The Shawshank Redemption' ]

,id,tags,title
0,278,"Drama,CrimeFramed in the 1940s for the double ...",The Shawshank Redemption


In [ ]:
dis = sorted(list(enumerate(sin[0])), reverse = True,key = lambda vec:vec[1])

In [ ]:
dis

[(0, np.float64(1.0)),
 (3709, np.float64(0.23539595453459988)),
 (9006, np.float64(0.2238141290858972)),
 (3649, np.float64(0.22019275302527214)),
 (2605, np.float64(0.20100756305184245)),
 (4068, np.float64(0.20100756305184245)),
 (6156, np.float64(0.20100756305184245)),
 (698, np.float64(0.19894589252079753)),
 (7324, np.float64(0.19767387315371682)),
 (1009, np.float64(0.19069251784911848)),
 (884, np.float64(0.1899342940993966)),
 (2963, np.float64(0.18802535827258876)),
 (7478, np.float64(0.1877810107252081)),
 (2991, np.float64(0.1860968420796942)),
 (715, np.float64(0.18582615562066462)),
 (7271, np.float64(0.18556740475630137)),
 (9520, np.float64(0.18148850216015694)),
 (2120, np.float64(0.17978662999019787)),
 (4201, np.float64(0.17912443020795962)),
 (2796, np.float64(0.17407765595569785)),
 (4063, np.float64(0.17407765595569785)),
 (4295, np.float64(0.17407765595569785)),
 (4490, np.float64(0.17407765595569785)),
 (4491, np.float64(0.17407765595569785)),
 (9718, np.float64

In [ ]:
for i in dis[0:5]:
  print (data_1.iloc[i[0]].title)

The Shawshank Redemption
Anything for Her
The Getaway
The Woodsman
Pusher II


In [ ]:
def recommend(movies):
  index = data_1[data_1['title'] == movies].index[0]
  dist = sorted(list(enumerate(sin[index])), reverse = True,key = lambda vec:vec[1])
  for i  in dist[0:5]:
    print (data_1.iloc[i[0]].title)

In [ ]:
recommend('Pusher II')

Pusher II
The Unforgivable
Shot Caller
Gotti
Angst
